import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { Footer, NavBar } from "@/components";

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "ТӨВ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoCondensed.variable}  font-sans`}>
        {/* <Header /> */}
        <NavBar />
        <div className="min-h-[calc(100vh-360px-125px)]">{children}</div>
        <Footer />
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
