import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { Footer, NavBar, QuickLinksSidebar } from "@/components";
import { headers } from "next/headers";

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "ТӨВ",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const pathname = headersList.get("x-pathname") || "";
  const isAdminPage = pathname.startsWith("/admin");

  return (
    <html lang="en">
      <body className={`${robotoCondensed.variable}  font-sans`}>
        {!isAdminPage && (
          <>
            {/* <Header /> */}
            <NavBar />
          </>
        )}
        <div className={isAdminPage ? "" : "min-h-[calc(100vh-360px-125px)]"}>
          {children}
        </div>
        {!isAdminPage && (
          <>
            <QuickLinksSidebar />
            <Footer />
          </>
        )}
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
